runtime: python27
api_version: 1
threadsafe: true
service: testing

# [START handlers]
handlers:
- url: /.*
  script: login.app
# [END handlers]

# [START libraries]
libraries:
- name: flask
  version: latest
# [END libraries]
